_target_: manipulation_lab.envs.tabletop.tasks.blocks_cfg.BlocksEnv
cfg:
  _target_: manipulation_lab.envs.tabletop.tasks.blocks_cfg.BlocksEnvCfg
  scene:
    _target_: manipulation_lab.envs.tabletop.tasks.blocks_cfg.BlocksSceneCfg
    robot: ${robot}
    num_envs: ${launcher.num_envs}
    env_spacing: 2.5