_target_: manipulation_lab.assets.robots.kinova_jaco2.N6S300Cfg
prim_path: "{ENV_REGEX_NS}/Robot"
init_state:
  pos: [0.0, 0.52, 0.0]
  rot: [-0.707, 0.0, 0.0, 0.707]
  lin_vel: [0.0, 0.0, 0.0]
  ang_vel: [0.0, 0.0, 0.0]
  joint_vel:
    ".*": 0.0
  joint_pos:
    j2n6s300_joint_1: 0.0
    j2n6s300_joint_2: 2.76
    j2n6s300_joint_3: 2.76
    j2n6s300_joint_4: 2.5
    j2n6s300_joint_5: 2.0
    j2n6s300_joint_6: 0.0
    j2n6s300_joint_finger_[1-3]: 0.2
    j2n6s300_joint_finger_tip_[1-3]: 0.2