_target_: manipulation_lab.envs.room.tasks.push_blocks.PushBlocksEnv
cfg:
  _target_: manipulation_lab.envs.room.tasks.push_blocks.PushBlocksEnvCfg
  mode: "train"
  use_domain_randomisation: True
  episode_length_s: 10
  scene:
    _target_: manipulation_lab.envs.room.tasks.push_blocks.PushBlocksSceneCfg
    robot: ${robot}
    num_envs: ${launcher.num_envs}
    env_spacing: 2.5