# DEFAULTS
defaults:
  - launcher: launcher
  - sim: sim
  - robot: franka
  - task: room/push_blocks
  - dataset_writer: dataset_writer
  - teleoperation: teleoperation
  - model: mlpfusion
  - encoder: r3m
  - encoder_weights: null
  - _self_

device: cuda

environment_seed: 0
max_attempts: 10

# Teleop mode
teleop: false
dagger: false
force_train_setup: true

# Controller config for policy deployment
controller:
  control_frequency: 30
  action_space: "delta_cartesian"
  camera_keys: ["sensors/wrist_camera/rgb", "sensors/scene_camera/rgb"]
  proprio_keys: ["robot/joint_pos", "robot/ee_pose_r"]
  sensor_keys: null
  oracle_keys: null
  model_use_structured_obs: false
  model_weights: "/home/ubuntu/Projects/manipulation_lab/weights/push_blocks/mlpfusion_r3m/mlpfusion_r3m_d10.pth"
  
openloop:
  dataset_dir: ["/home/ubuntu/Projects/manipulation_lab/datasets/room/push_blocks/clean/"]
  episode_idx: 0