defaults:
  - model: mlpfusion
  - encoder: resnet18
  - _self_

device: cuda

use_pretrained_weights: false
pretrained_weights_path: "/home/ubuntu/Projects/manipulation_lab/weights/test_model.pth"

dataset:
  dataset_dirs: [
    "/home/ubuntu/Projects/manipulation_lab/datasets/room/blocks/clean/",
    ]
  camera_keys: ["sensors/wrist_camera/rgb", "sensors/left_shoulder_camera/rgb"]
  action_keys: ["expert/ee_deltas", "expert/gripper_deltas"]
  proprio_keys: ["robot/joint_pos"]
  sensor_keys: null
  sequence_length: 1
  stride: 1
  structured_obs: false
  splits:
    train: 0.8
    val: 0.1
    test: 0.1
  seed: 0

# Use default dataloader
dataloader:
  batch_size: 16
  shuffle: true
  num_workers: 0 # Be cautious raising above 0 - OOM errors 

optim:
  lr: 1e-5
epochs: 10
train:
  save_dir: /home/ubuntu/Projects/manipulation_lab/weights
  save_name: test_model


custom_dataset: null
# Use custom dataloader. _target_ must be a valid torch.DataLoader
custom_dataloader: null
  #_target_: path.to.custom.dataloader.class
  #dataset: _target_ must be a valid torch.Dataset
  #  _target_: path.to.custom.dataset.class
  # ... etc.





