defaults:
  - model: mlp
  - encoder: resnet18
  - _self_

device: cuda

use_pretrained_weights: false
pretrained_weights_path: null

dataset:
  dataset_dirs: [
    "/home/ubuntu/Projects/manipulation_lab/datasets/room/push_blocks/clean/",
    "/home/ubuntu/Projects/manipulation_lab/datasets/room/push_blocks/dagger/"
    ]
  dataset_source_weights:
    clean: 3.0
    dagger: 1.0
  camera_keys: #["sensors/wrist_camera/rgb", "sensors/scene_camera/rgb"]
  action_keys: ["expert/ee_deltas", "expert/gripper_deltas"]
  proprio_keys: ["robot/joint_pos", "robot/ee_pose_r"]
  sensor_keys: null
  oracle_keys: [
    "oracle/cuboid_blue/pose_r",
    "oracle/cone_left/pose_r", 
    "oracle/cone_right/pose_r"
  ]
  sequence_length: 1
  stride: 1
  structured_obs: false
  splits:
    train: 0.8
    val: 0.1
    test: 0.1
  seed: 0

# Use default dataloader
dataloader:
  batch_size: 16
  shuffle: true
  num_workers: 0 # Be cautious raising above 0 - OOM errors 

optim:
  lr: 1e-5
epochs: 10
train:
  save_dir: /home/ubuntu/Projects/manipulation_lab/weights/push_blocks/oracle
  save_name: mlp_oracle_d8


custom_dataset: null
# Use custom dataloader. _target_ must be a valid torch.DataLoader
custom_dataloader: null
  #_target_: path.to.custom.dataloader.class
  #dataset: _target_ must be a valid torch.Dataset
  #  _target_: path.to.custom.dataset.class
  # ... etc.





