defaults:
  - model: mlpfusion
  - encoder: r3m
  - _self_

device: cuda

use_pretrained_weights: false
pretrained_weights_path: null

dataset:
  dataset_dirs: [
    "/home/ubuntu/Projects/manipulation_lab/datasets/room/push_blocks/clean/",
    "/home/ubuntu/Projects/manipulation_lab/datasets/test/room/push_blocks/dagger/"
    ]
  dataset_source_weights:
    clean: 2.0
    dagger: 1.0
  camera_keys: ["sensors/wrist_camera/rgb", "sensors/scene_camera/rgb"]
  action_keys: ["expert/ee_deltas", "expert/gripper_deltas"]
  proprio_keys: ["robot/joint_pos", "robot/ee_pose_r"]
  sensor_keys: null
  oracle_keys: null
  sequence_length: 2
  stride: 2
  structured_obs: false
  splits:
    train: 0.8
    val: 0.1
    test: 0.1
  seed: 0

dataloader:
  batch_size: 16
  shuffle: true
  num_workers: 0

optim:
  lr: 1e-5
epochs: 15
train:
  save_dir: /home/ubuntu/Projects/manipulation_lab/weights/stack_blocks/mlpfusion_r3m
  save_name: mlpfusion_r3m_d1

custom_dataset: null
custom_dataloader: null




